### PR TITLE
Create bot-ビットフライヤー

### PR DESCRIPTION
**Pull request by miyagon**
Install-Package BitflyerApi

### CODE REVIEW

**Comment by kobake** [comment]
what? any mistake?

**Comment by miyagon** [comment]
I'm sorry. I made a mistake.

**Comment by kobake** [comment]
Had you tried to make PR in your repository? If so, you need to select not original repository but yours in combobox when creating PR.

pr

**Comment by kobake** [comment]
I close This PR. Feel free to ask more.

**Pull request closed without merging**
